version: "1"
services:
  spark:
    container_name: spark-playground
    build: ./spark
    ports:
      - "4040:4040"
      - "7077:7077"
      - "6066:6066"
    volumes:
       - ./app/spark:/workspace
  hadoop:
    container_name: hadoop-playground
    build: ./hadoop
    volumes:
      - ./app/hadoop:/workspace
  jupyter:
    container_name: jupyter-playground
    image: jupyter/pyspark-notebook
    ports:
      - 8889:8888
    volumes:
      - ./app/jupyter:/home/jovyan/work